// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Data;

#nullable disable

namespace Product.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260913180821_addCourse")]
    partial class addCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseHours")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseHours = 60,
                            Degree = 100,
                            DepartmentId = 1,
                            MinDegree = 50,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            CourseHours = 45,
                            Degree = 100,
                            DepartmentId = 1,
                            MinDegree = 50,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            CourseHours = 60,
                            Degree = 100,
                            DepartmentId = 1,
                            MinDegree = 50,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 4,
                            CourseHours = 45,
                            Degree = 100,
                            DepartmentId = 2,
                            MinDegree = 50,
                            Name = "System Analysis"
                        },
                        new
                        {
                            Id = 5,
                            CourseHours = 50,
                            Degree = 100,
                            DepartmentId = 2,
                            MinDegree = 50,
                            Name = "Business Intelligence"
                        },
                        new
                        {
                            Id = 6,
                            CourseHours = 60,
                            Degree = 100,
                            DepartmentId = 3,
                            MinDegree = 50,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 7,
                            CourseHours = 60,
                            Degree = 100,
                            DepartmentId = 3,
                            MinDegree = 50,
                            Name = "Deep Learning"
                        });
                });

            modelBuilder.Entity("Product.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TraineeId");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Degree = 85,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 2,
                            Degree = 78,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 3,
                            Degree = 92,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 1,
                            Degree = 95,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Degree = 88,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 3,
                            Degree = 91,
                            TraineeId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseId = 4,
                            Degree = 82,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 8,
                            CourseId = 5,
                            Degree = 76,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 9,
                            CourseId = 4,
                            Degree = 90,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 10,
                            CourseId = 5,
                            Degree = 87,
                            TraineeId = 4
                        },
                        new
                        {
                            Id = 11,
                            CourseId = 6,
                            Degree = 94,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 12,
                            CourseId = 7,
                            Degree = 89,
                            TraineeId = 5
                        },
                        new
                        {
                            Id = 13,
                            CourseId = 6,
                            Degree = 86,
                            TraineeId = 6
                        },
                        new
                        {
                            Id = 14,
                            CourseId = 7,
                            Degree = 93,
                            TraineeId = 6
                        });
                });

            modelBuilder.Entity("Product.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Information Systems"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "Artificial Intelligence"
                        });
                });

            modelBuilder.Entity("Product.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InstructorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorId = 1,
                            Address = "Cairo, Egypt",
                            DepartmentId = 1,
                            Email = "ahmed.hassan@example.com",
                            Image = "https://i.pravatar.cc/150?img=11",
                            Name = "Dr. Ahmed Hassan",
                            PhoneNumber = "01012345678",
                            Salary = 25000m
                        },
                        new
                        {
                            InstructorId = 2,
                            Address = "Giza, Egypt",
                            DepartmentId = 1,
                            Email = "sara.mohamed@example.com",
                            Image = "https://i.pravatar.cc/150?img=45",
                            Name = "Dr. Sara Mohamed",
                            PhoneNumber = "01123456789",
                            Salary = 22000m
                        },
                        new
                        {
                            InstructorId = 3,
                            Address = "Alexandria, Egypt",
                            DepartmentId = 2,
                            Email = "omar.ali@example.com",
                            Image = "https://i.pravatar.cc/150?img=12",
                            Name = "Dr. Omar Ali",
                            PhoneNumber = "01234567890",
                            Salary = 24000m
                        },
                        new
                        {
                            InstructorId = 4,
                            Address = "Cairo, Egypt",
                            DepartmentId = 3,
                            Email = "menna.adel@example.com",
                            Image = "https://i.pravatar.cc/150?img=49",
                            Name = "Dr. Menna Adel",
                            PhoneNumber = "01098765432",
                            Salary = 27000m
                        });
                });

            modelBuilder.Entity("Product.Models.Productt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Product.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraineeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            DepartmentId = 1,
                            Image = "https://i.pravatar.cc/150?img=12",
                            Name = "Ahmed Hassan"
                        },
                        new
                        {
                            TraineeId = 2,
                            DepartmentId = 1,
                            Image = "https://i.pravatar.cc/150?img=47",
                            Name = "Zeinab Amr"
                        },
                        new
                        {
                            TraineeId = 3,
                            DepartmentId = 2,
                            Image = "https://i.pravatar.cc/150?img=33",
                            Name = "Omar Khaled"
                        },
                        new
                        {
                            TraineeId = 4,
                            DepartmentId = 2,
                            Image = "https://i.pravatar.cc/150?img=44",
                            Name = "Mariam Ali"
                        },
                        new
                        {
                            TraineeId = 5,
                            DepartmentId = 3,
                            Image = "https://i.pravatar.cc/150?img=13",
                            Name = "Youssef Mohamed"
                        },
                        new
                        {
                            TraineeId = 6,
                            DepartmentId = 3,
                            Image = "https://i.pravatar.cc/150?img=32",
                            Name = "Salma Ahmed"
                        });
                });

            modelBuilder.Entity("Product.Models.Course", b =>
                {
                    b.HasOne("Product.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Product.Models.CourseResult", b =>
                {
                    b.HasOne("Product.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Product.Models.Instructor", b =>
                {
                    b.HasOne("Product.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Product.Models.Trainee", b =>
                {
                    b.HasOne("Product.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Product.Models.Course", b =>
                {
                    b.Navigation("CourseResults");
                });

            modelBuilder.Entity("Product.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("Product.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
