// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Data;

#nullable disable

namespace Product.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260912122256_AddTraineeImage")]
    partial class AddTraineeImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Information Systems"
                        });
                });

            modelBuilder.Entity("Product.Models.Productt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Vivo",
                            Category = "Smartphones",
                            Description = "Excellent smartphone with a high-resolution camera and great display.",
                            Image = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500",
                            IsActive = true,
                            Name = "Vivo V50 5G",
                            Price = 15000m,
                            Rating = 5,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Lenovo",
                            Category = "Laptops",
                            Description = "Durable and powerful laptop, perfect for programming and development.",
                            Image = "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500",
                            IsActive = true,
                            Name = "Lenovo ThinkPad",
                            Price = 35000m,
                            Rating = 4,
                            Stock = 20
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Sony",
                            Category = "Accessories",
                            Description = "Noise-cancelling wireless earbuds with crystal clear sound.",
                            Image = "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500",
                            IsActive = true,
                            Name = "Sony Wireless Earbuds",
                            Price = 1200m,
                            Rating = 4,
                            Stock = 100
                        });
                });

            modelBuilder.Entity("Product.Models.Trainee", b =>
                {
                    b.Property<int>("TraineeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TraineeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TraineeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            TraineeId = 1,
                            DepartmentId = 1,
                            Image = "https://i.pravatar.cc/150?img=12",
                            Name = "Ahmed"
                        },
                        new
                        {
                            TraineeId = 2,
                            DepartmentId = 1,
                            Image = "https://i.pravatar.cc/150?img=47",
                            Name = "Zeinab"
                        },
                        new
                        {
                            TraineeId = 3,
                            DepartmentId = 2,
                            Image = "https://i.pravatar.cc/150?img=33",
                            Name = "Omar"
                        });
                });

            modelBuilder.Entity("Product.Models.Trainee", b =>
                {
                    b.HasOne("Product.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Product.Models.Department", b =>
                {
                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
